name: Nested Workflow

on:
  workflow_call:
    inputs:
      ambiente:
        required: true
        type: string

jobs:
  tarefa-nested:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando o Nested no repo2! Ambiente recebido -> ${{ inputs.ambiente }}"
