name: Nested Workflow

on:
  workflow_call:
    inputs:
      ambiente:
        required: true
        type: string

jobs:
  passos:
    uses: joaobcandido/repo-reusable/.github/workflows/passos.yml@main
    with:
      ambiente: 'Produção'
